name: Validate file structure and contents

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Validate files
        run: python .github/scripts/validate-files.py
